[project]
name = "frag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.22.1",
    "awscli>=1.44.68",
    "boto3>=1.42.78",
    "chainlit>=2.10.0",
    "dependency-injector>=4.49.0",
    "fastmcp>=3.1.0",
    "h5py>=3.15.1",
    "langchain>=1.2.12",
    "langchain-google-genai>=4.2.1",
    "langchain-mcp-adapters>=0.2.1",
    "langchain-mistralai>=1.1.1",
    "langchain-ollama>=1.0.1",
    "langgraph>=1.0.10",
    "langgraph-checkpoint-aws>=1.0.6",
    "langgraph-checkpoint-postgres>=3.0.5",
    "langgraph-checkpoint-sqlite>=3.0.3",
    "loguru>=0.7.3",
    "open-clip-torch>=3.3.0",
    "pillow>=12.1.1",
    "psycopg[binary]>=3.3.3",
    "pydantic-settings>=2.13.1",
    "pytest-cov>=7.1.0",
    "python-dotenv>=1.2.2",
    "qdrant-client>=1.17.0",
    "s3fs>=0.4.2",
    "torch>=2.10.0",
    "transformers>=5.2.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "pytest-mock>=3.15.1",
    "ruff>=0.15.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages=["src/frag"]

[tool.pytest.ini_options]
# anything in add opts (options) gets added to the pytest command.
addopts = [
    # -ra: show short summary of all non-passing tests at the end
    "-ra",
    # -v:  show each test name and its pass/fail status
    "-v",
    # the import mode controls how pytest imports modules. by default, the imports are done by adding the parent directory prepended to the sys.path. importlib means that sys.path is not touched and importlib module is used instead for imports. This (importlib) is the modern recommendation.
    "--import-mode=importlib",
    # --cov=frag: that tells pytest-cov to track coverage of my package
    "--cov=frag",
    # this creates a html report where you can actually look at the file and see which lines are covered and which not
    "--cov-report=html:reports/htmlcov",
    # this adds a terminal report with an extra column showing missing line numbers and it also skips files which are 100% covered
    "--cov-report=term-missing:skip-covered"
]
# this tells pytest where to search for test files - by restricting to tests folder we ensure that things are a little faster - pytest does not spend time walking through src folder
testpaths = ["tests"]
filterwarnings = [
    # langchain mcp server is throwing this internal warning and I am going to suppress it since I can't do anything about it until they fix it
    'ignore:Use `streamable_http_client` instead:DeprecationWarning:contextlib',
]

[tool.coverage.run]
omit = [
    "src/frag/data_manager/dynamo_db_connector.py",
    "src/frag/data_manager/session_data_table.py",
    "src/frag/exploration/*",
    "src/frag/mcp_server/mcp_client.py",
]
