line-length = 88

extend-exclude = [
    "src/exploration/data_exploration.py",
    "src/exploration/langgraph_exploration.py",
]
[lint]
extend-select = [
    "D",  # pydocstyle (docstring formatting)
    "E",  # pydocstyle (standard errors) - subset in default
    "F",  # pyflakes (logical errors) - present in default
    "W",  # pycodestyle warning
    "I",  # isort (for sorting imports)
]
ignore = [
    "D203",   # One-blank-line-before-class is mutually exclusive.
    "D213",   # Multi-line-summary-first-line is mutually exclusive.
]

[lint.pydocstyle]
convention = "google"

[format]
docstring-code-format = true

#     "D100",   # Reverse; Missing docstring in public module
#     "D102",   # Reverse; Missing docstring in public method
#     "D103",   # Reverse; Missing docstring in public function
#     "D107",   # Reverse; Missing docstring in `__init__`
