# VLM agent for generating sample images or converting provided ones to descriptions
# Possible names:
# 1. qwen3-vl:4b-thinking
# 2. qwen3-vl:8b-thinking
# 3. gemma-3-27b-it
# 4. mock
# 5. mistral-large-latest
vlm_agent:
  _target_: src.utils.model_factory.get_llm_provider
  # name: mistral-large-latest
  name: mock
  temp: 0.6
  use_rate_limiter: true

# for the langchain InMemoryRateLimiter - it uses a token (not LLM tokens) bucket model
rate_limiter:
  # this is the rate at which tokens get added to the bucket - it is kept far below the actual threshold to decrease risk of rate limiting even further and because there is also a 500k tokens per minute rate limit which is not captured
  requests_per_second: 0.2
  # this sets the frequency with which it checks if tokens are available to make a request
  check_every_n_seconds: 1
  # this is the size of the bucket - allows a burst of requests if the rate limiting is actually long term rather than strictly per second
  max_bucket_size: 1.0

# this is for any api keys that I might require directly
api_keys:
  mistral: ${oc.env:MISTRAL_API_KEY}
