"""Config for Data Handling and Processing."""
from pydantic import BaseModel, ConfigDict, HttpUrl, FilePath

class DataProcessingConfig(BaseModel):
    """Config for data processing pipeline."""
    model_config = ConfigDict(frozen=True)

    # this is the dimensionality of the embedding generated by marqo-fashionSigLIP
    embedding_size: int = 768

    # this is the number of images / texts that are taken in a single batch to generate their embeddings using the embedding model. 512 worked fine.
    embedding_batch_size: int = 512

    # this is the number of datapoints we fetch at one time from the fashion-gen dataset. Best for it to be some integer multiple of the batch size. Not so large that it does not fit in RAM. Without writing image to payload, the process is really fast.
    data_fetch_batch_size: int = 4096

    # this is the batch size - fetched using scroll - that is used during the migration process
    migration_batch_size: int = 1024

    # this is the batch size used during payload updates - used during the payload dictionary update process
    payload_update_batch_size: int = 1024

    # this is the batch size of uploads when uploading the collection to the qdrant db using upload_collection / upload_points
    upload_batch_size: int = 512

    # this is the number of parallel workers used during collection upload
    upload_parallel: int = 4

class VectorDBConfig(BaseModel):
    """Config for setup and use of vector db."""
    model_config = ConfigDict(frozen=True)

    # this is the url location of the qdrant docker client
    vector_store_network_path: HttpUrl = 'http://localhost:6333'

    # qdrant allows two api's - rest and grpc. grpc is more performant while rest api is more convenient. the docs recommend using grpc if we are already familiar with qdrant and are trying to optimize the performance of our application.
    prefer_grpc: bool = True

    # this is the name of the collection in qdrant
    collection_name: str = 'fashion_gen'

    # this is the model used to generated embeddings (multi-modal)
    embedding_model: str = 'hf-hub:Marqo/marqo-fashionSigLIP'

    # this flag controls if the collection is recreated if it already exists. This will remain true while I have not generated the full collection.
    recreate: bool = False

    # when inserting the embeddings in to qdrant, since they are multi-modal, I am inserting them as named vectors. Below 2 are the names.
    image_vectors_name: str = 'images'
    text_vectors_name: str = 'texts'

    # this flag controls whether or not we use Memory Map storage in qdrant (also called on-disk storage) from the start - which is recommended for large collections
    vectors_on_disk: bool = True

    # this flag control if we move the Hnsw graph onto the disk or not
    hnsw_on_disk: bool = True

    # this flag controls if we write the payload onto the disk or keep it in memory (RAM)
    payload_on_disk: bool = True

    # this value controls the number of vectors after which we start building HNSW graphs (20k is default)
    indexing_threshold: int = 20000

class FashionGenConfig(BaseModel):
    """Config for the actual dataset."""
    model_config = ConfigDict(frozen=True)
    # TODO: fix this later

    # this is the location of the hdf5 file for the fashion-gen dataset - this is downloaded dataset from kaggle. But it is the smaller version. There is another version with more high resolution images.
    hdf5_path: FilePath = '/mnt/windows/Users/lordh/Documents/Svalbard/Data/fashion-gen/fashiongen_256_256_train.h5'

    # these are the string attributes from the database that we want to capture
    string_attributes: list[str] = ['input_brand', 'input_category', 'input_composition', 'input_department', 'input_gender', 'input_name', 'input_season', 'input_subcategory', 'input_description']

    # this is the encoding used by the strings in the fashion-gen dataset
    string_codec: str = 'latin-1'

    # The HDF5 file is a sort of dictionary where each key is a separate dataset. The values of all datasets are aligned. Below is the name of the images dataset.
    images_key: str = 'input_image'

    # The HDF5 file is a sort of dictionary where each key is a separate dataset. The values of all datasets are aligned. Below is the name of the descriptions dataset.
    descriptions_key: str = 'input_description'

    # The HDF5 file is a sort of dictionary where each key is a separate dataset. The values of all datasets are aligned. Below is the name of the price (MSRP) dataset.
    prices_key: str = 'input_msrpUSD'

    # The HDF5 file is a sort of dictionary where each key is a separate dataset. The values of all datasets are aligned. Below is the name of the category dataset.
    categories_key: str = 'input_category'

    # The HDF5 file is a sort of dictionary where each key is a separate dataset. The values of all datasets are aligned. Below is the name of the index dataset. index_2 is aligned with the sequential index of the elements in the dataset, while index is not.
    index_key: str = 'index_2'

    # this is the total number of datapoints present in the fashion-gen dataset
    num_datapoints: int = 260_490

    # these are the categories to which the items in the database belong
    product_categories: list[str] = ["CLUTCHES & POUCHES", "POUCHES & DOCUMENT HOLDERS", "BOOTS", "BACKPACKS", "SWEATERS", "SWIMWEAR", "MONKSTRAPS", "JEWELRY", "DUFFLE & TOP HANDLE BAGS", "JEANS", "LACE UPS", "SKIRTS", "DUFFLE BAGS", "TOPS", "DRESSES", "MESSENGER BAGS & SATCHELS", "SOCKS", "LOAFERS", "ESPADRILLES", "UNDERWEAR & LOUNGEWEAR", "BAG ACCESSORIES", "HATS", "SANDALS", "JACKETS & COATS", "MESSENGER BAGS", "GLOVES", "TRAVEL BAGS", "LINGERIE", "SCARVES", "KEYCHAINS", "BLANKETS", "TIES", "FLATS", "SHORTS", "PANTS", "SUITS & BLAZERS", "TOTE BAGS", "HEELS", "EYEWEAR", "BRIEFCASES", "JUMPSUITS", "FINE JEWELRY", "BELTS & SUSPENDERS", "SHIRTS", "BOAT SHOES & MOCCASINS", "SNEAKERS", "POCKET SQUARES & TIE BARS", "SHOULDER BAGS"]

class DataConfig(BaseModel):
    """Overal config class for data."""
    model_config = ConfigDict(frozen=True)

    data_processing: DataProcessingConfig = DataProcessingConfig()
    vector_db: VectorDBConfig = VectorDBConfig()
    fashion_gen: FashionGenConfig = FashionGenConfig()
