"""Config for Data Handling and Processing."""

from typing import Callable

from pydantic import BaseModel, ConfigDict, FilePath, Field, DirectoryPath
from pydantic_settings import BaseSettings, SettingsConfigDict

class FashionGenAWSConfig(BaseModel):
    """Config for uploading / managing fashion gen dataset on AWS S3."""
    model_config = ConfigDict(frozen=True, validate_default=True)

    s3_bucket_name: str = 'frag-fashion-gen-dataset'

    # the name of the fashion gen dataset hdf5 file when uploaded to the s3 bucket
    dataset_object_name: str = 'fashion_gen.h5'

    # Tuning: the default s3fs block_size is 50 MB. Our access pattern
    # is non-sequential random access to individual rows, so 50 MB blocks
    # means we download ~50 MB to use ~100 KB. 200 KB is a better trade-off
    # that reduces wasted bandwidth by ~256× without hurting latency.
    # I have verified that the unit is bytes since they set it as 50 * 2**20 for default
    s3fs_block_size: int = 100 * 1024

    # the s3 key for the metadata file
    fashion_gen_metadata_s3_key: str = "metadata/fashion_gen_metadata.parquet"

    # this function gives the s3 key given a fashion gen image index corresponding to the location where the image is stored in s3
    fashion_gen_image_s3_key_lambda: Callable[[int], str] = lambda idx: f"images/{idx // 1000:03d}/{idx}.png"

class AWSVectorDBCreation(BaseModel):
    """Config for generating embeddings and creating vector db on AWS."""
    model_config = ConfigDict(frozen=True, validate_default=True)

    # this is the size of the embedding returned by Amazon Nova. Options are 3072, 1024, 384, 256
    embedding_dim: int = 1024

    # this is the number of records we'll have per jsonl file (the limit is 100k)
    records_per_jsonl_file: int = 50_000

    # this is the folder in which the jsonl files will be stored
    jsonl_folder_path: DirectoryPath = "data/jsonl_files"

    # this is the name of the bucket on s3 which is used for the jsonl files and for the embedding outputs
    embedding_s3_bucket_name: str = "frag-fashion-gen-embeddings"

    # this function gives the s3 key given a jsonl file name (not path) corresponding to where the file is located in the s3 bucket
    jsonl_s3_key_lambda: Callable[[str], str] = lambda file_name: f"jsonl_files/{file_name}"

    # this is the folder name for the jsonl files inside their s3 bucket (it should match the value for jsonl_s3_key_lambda)
    jsonl_s3_folder_name: str = "jsonl_files"

    # this is the name of the folder in s3 embedding_s3_bucket_name bucket where the output of the embedding jobs will be saved
    embedding_output_folder_s3: str = "embedding_output"

    # this is the model to use to generate the embeddings
    embedding_model_id: str = "amazon.nova-2-multimodal-embeddings-v1:0"

    # this is the name of the role that bedrock assumes while executing my batch jobs
    bedrock_batch_inference_role_name: str = "BedrockBatchInferenceRole"

    # this is the name of the policy that the bedrock_batch_inference_role_name role uses to allow it access to AWS S3
    bedrock_batch_s3_access_policy_name: str = "BedrockBatchS3Access"

    # this is the prefix used to submit embedding jobs to model with id embedding_model_id
    batch_embedding_job_prefix: str = "frag-fashion-gen-embedding-job"

class ChainlitPersistenceConfig(BaseSettings):
    """Config for the S3 Bucket and the Dynamo DB table used by chainlit."""

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        frozen=True,
        extra="ignore",
        env_ignore_empty=True,
        validate_default=True,
    )

    # from the .env file
    s3_bucket_name: str = Field(
        validation_alias="aws_s3_chainlit_persistence_bucket_name"
    )
    dynamodb_table_name: str = Field(
        validation_alias="aws_dynamodb_chainlit_persistence_table_name"
    )

    # the value can be different for different resources - so it is permissible to have region configs all over
    s3_region: str = "us-east-1"


class DataProcessingConfig(BaseModel):
    """Config for data processing pipeline."""

    model_config = ConfigDict(frozen=True, validate_default=True)

    # this is for creating embeddings and creating vector db on aws
    aws_vec_db_gen: AWSVectorDBCreation = AWSVectorDBCreation()

    # this is the dimensionality of the embedding generated by marqo-fashionSigLIP
    embedding_size: int = 768

    # this is the number of images / texts that are taken in a single batch to generate their embeddings using the embedding model. 512 worked fine.
    embedding_batch_size: int = 512

    # this is the number of datapoints we fetch at one time from the fashion-gen dataset. Best for it to be some integer multiple of the batch size. Not so large that it does not fit in RAM. Without writing image to payload, the process is really fast.
    data_fetch_batch_size: int = 4096

    # this is the batch size - fetched using scroll - that is used during the migration process
    migration_batch_size: int = 1024

    # this is the batch size used during payload updates - used during the payload dictionary update process
    payload_update_batch_size: int = 1024

    # this is the batch size of uploads when uploading the collection to the qdrant db using upload_collection / upload_points
    upload_batch_size: int = 512

    # this is the number of parallel workers used during collection upload
    upload_parallel: int = 4


class VectorDBConfig(BaseModel):
    """Config for setup and use of vector db."""

    model_config = ConfigDict(frozen=True, validate_default=True)

    # this is the url location of the qdrant docker client - this can't actually be an http url since the actual value expected in the receiver is str and it throws an error if I set it as HttpUrl
    vector_store_network_path: str = "http://localhost:6333"

    # qdrant allows two api's - rest and grpc. grpc is more performant while rest api is more convenient. the docs recommend using grpc if we are already familiar with qdrant and are trying to optimize the performance of our application.
    prefer_grpc: bool = True

    # this is the name of the collection in qdrant - the collection name for the full collection using marqo-fashion siglip is fashion_gen, but a lot of stuff needs to change for that to work
    collection_name: str = "nova_fashion_gen"

    # this is the model used to generated embeddings (multi-modal)
    embedding_model: str = "hf-hub:Marqo/marqo-fashionSigLIP"

    # this flag controls if the collection is recreated if it already exists. This will remain true while I have not generated the full collection.
    recreate: bool = False

    # when inserting the embeddings in to qdrant, since they are multi-modal, I am inserting them as named vectors. Below 2 are the names.
    image_vectors_name: str = "images"
    text_vectors_name: str = "texts"

    # this flag controls whether or not we use Memory Map storage in qdrant (also called on-disk storage) from the start - which is recommended for large collections
    vectors_on_disk: bool = True

    # this flag control if we move the Hnsw graph onto the disk or not
    hnsw_on_disk: bool = True

    # this flag controls if we write the payload onto the disk or keep it in memory (RAM)
    payload_on_disk: bool = True

    # this value controls the number of vectors after which we start building HNSW graphs (20k is default)
    indexing_threshold: int = 20000


class FashionGenConfig(BaseModel):
    """Config for the actual dataset."""

    model_config = ConfigDict(frozen=True, validate_default=True)
    # TODO: fix this later

    # this is the location of the hdf5 file for the fashion-gen dataset - this is downloaded dataset from kaggle. But it is the smaller version. There is another version with more high resolution images.
    hdf5_path: FilePath = "/mnt/windows/Users/lordh/Documents/Svalbard/Data/fashion-gen/fashiongen_256_256_train.h5"

    # these are the string attributes from the database that we want to capture
    string_attributes: list[str] = [
        "input_brand",
        "input_category",
        "input_composition",
        "input_department",
        "input_gender",
        "input_name",
        "input_season",
        "input_subcategory",
        "input_description",
    ]

    # this is the encoding used by the strings in the fashion-gen dataset
    string_codec: str = "latin-1"

    # The HDF5 file is a sort of dictionary where each key is a separate dataset. The values of all datasets are aligned. Below is the name of the images dataset.
    images_key: str = "input_image"

    # The HDF5 file is a sort of dictionary where each key is a separate dataset. The values of all datasets are aligned. Below is the name of the descriptions dataset.
    descriptions_key: str = "input_description"

    # The HDF5 file is a sort of dictionary where each key is a separate dataset. The values of all datasets are aligned. Below is the name of the price (MSRP) dataset.
    prices_key: str = "input_msrpUSD"

    # The HDF5 file is a sort of dictionary where each key is a separate dataset. The values of all datasets are aligned. Below is the name of the category dataset.
    categories_key: str = "input_category"

    # The HDF5 file is a sort of dictionary where each key is a separate dataset. The values of all datasets are aligned. Below is the name of the index dataset. index_2 is aligned with the sequential index of the elements in the dataset, while index is not.
    index_key: str = "index_2"

    # this is the total number of datapoints present in the fashion-gen dataset
    num_datapoints: int = 260_490

    # these are the categories to which the items in the database belong
    product_categories: list[str] = [
        "CLUTCHES & POUCHES",
        "POUCHES & DOCUMENT HOLDERS",
        "BOOTS",
        "BACKPACKS",
        "SWEATERS",
        "SWIMWEAR",
        "MONKSTRAPS",
        "JEWELRY",
        "DUFFLE & TOP HANDLE BAGS",
        "JEANS",
        "LACE UPS",
        "SKIRTS",
        "DUFFLE BAGS",
        "TOPS",
        "DRESSES",
        "MESSENGER BAGS & SATCHELS",
        "SOCKS",
        "LOAFERS",
        "ESPADRILLES",
        "UNDERWEAR & LOUNGEWEAR",
        "BAG ACCESSORIES",
        "HATS",
        "SANDALS",
        "JACKETS & COATS",
        "MESSENGER BAGS",
        "GLOVES",
        "TRAVEL BAGS",
        "LINGERIE",
        "SCARVES",
        "KEYCHAINS",
        "BLANKETS",
        "TIES",
        "FLATS",
        "SHORTS",
        "PANTS",
        "SUITS & BLAZERS",
        "TOTE BAGS",
        "HEELS",
        "EYEWEAR",
        "BRIEFCASES",
        "JUMPSUITS",
        "FINE JEWELRY",
        "BELTS & SUSPENDERS",
        "SHIRTS",
        "BOAT SHOES & MOCCASINS",
        "SNEAKERS",
        "POCKET SQUARES & TIE BARS",
        "SHOULDER BAGS",
    ]


class DataConfig(BaseModel):
    """Overal config class for data."""

    model_config = ConfigDict(frozen=True, validate_default=True)

    data_processing: DataProcessingConfig = DataProcessingConfig()
    vector_db: VectorDBConfig = VectorDBConfig()
    fashion_gen: FashionGenConfig = FashionGenConfig()
    chainlit_persistence: ChainlitPersistenceConfig = ChainlitPersistenceConfig()
    aws_fashion_gen: FashionGenAWSConfig = FashionGenAWSConfig()
