"""The pydantic schemas used to constrain LLM outputs."""

from typing import Literal, Optional

from pydantic import BaseModel, Field


class RequiredClothes(BaseModel):
    """Class to constrain LLM output when generating clothing item descriptions."""

    required_clothes_descriptions: list[str] = Field(
        min_length=1,
        description=(
            "List of descriptions of clothing items that satisfy the user's"
            "requests. One description per index."
        ),
    )


class NumRecommendations(BaseModel):
    """Constrains LLM output when getting the no. of reco's in the user request."""

    num_recommendations: int = Field(
        ge=1,
        le=10,
        description=(
            "Number of recommendations specified by the user, 0 if no"
            "specification made by the user."
        ),
    )


class SingleImageDescription(BaseModel):
    """Constrains LLM output when generating image descriptions."""

    image_description: str = Field(
        min_length=20,
        description="Description of the image as mentioned in the instructions.",
    )


class ValidCategories(BaseModel):
    """List of valid dataset categories to which the clothing item must belong."""

    categories: list[
        Literal[
            "CLUTCHES & POUCHES",
            "POUCHES & DOCUMENT HOLDERS",
            "BOOTS",
            "BACKPACKS",
            "SWEATERS",
            "SWIMWEAR",
            "MONKSTRAPS",
            "JEWELRY",
            "DUFFLE & TOP HANDLE BAGS",
            "JEANS",
            "LACE UPS",
            "SKIRTS",
            "DUFFLE BAGS",
            "TOPS",
            "DRESSES",
            "MESSENGER BAGS & SATCHELS",
            "SOCKS",
            "LOAFERS",
            "ESPADRILLES",
            "UNDERWEAR & LOUNGEWEAR",
            "BAG ACCESSORIES",
            "HATS",
            "SANDALS",
            "JACKETS & COATS",
            "MESSENGER BAGS",
            "GLOVES",
            "TRAVEL BAGS",
            "LINGERIE",
            "SCARVES",
            "KEYCHAINS",
            "BLANKETS",
            "TIES",
            "FLATS",
            "SHORTS",
            "PANTS",
            "SUITS & BLAZERS",
            "TOTE BAGS",
            "HEELS",
            "EYEWEAR",
            "BRIEFCASES",
            "JUMPSUITS",
            "FINE JEWELRY",
            "BELTS & SUSPENDERS",
            "SHIRTS",
            "BOAT SHOES & MOCCASINS",
            "SNEAKERS",
            "POCKET SQUARES & TIE BARS",
            "SHOULDER BAGS",
        ]
    ] = Field(
        min_length=1,
        description=(
            "A list of all the categories to which the clothing item whose "
            "description is provided, belongs."
        ),
    )


class MatchedImageId(BaseModel):
    """The id of the image which was matched to the input description."""
    image_id: int = Field(..., description="Id of the best matched image")


class UpdatedUserRequest(BaseModel):
    """Ids of the relevant images and the updated text for the user input."""
    relevant_image_indexes: list[int] = Field(min_length=0, description="The indexes of the images which are relevant. If none are relevant this can be left empty.")
    updated_user_query: str = Field(..., description="The combined comprehensive and concise query that incorporates both the new user query, and, if relevant, the old user query.")

class AgentState(BaseModel):
    """The stateful component of the agent orchestration in langgraph.

    Attributes:
        has_input_images (bool): Indicates if the user input has any images.
        input_images_path (list[str]): List of string relative paths to the images
            uploaded by the user.
        input_text (str): This is the text part of the user request.
        vlm_instructions (str): This is the description of what the vision language
            model should focus on when analysing the user input image(s). This is
            generated by an LLM, rather than a fixed prompt.
        num_recommendations (int): This is the number of clothing items / accessories
            that the user should be recommended. This can come from the user themselves
            or can be the default value.
        input_images_descriptions (list[str]): These are the descriptions of the user
            supplied images which are obtained from the vision language model. The
            instructions for these are in `vlm_instructions`.
        required_clothes_descriptions (list[str]): These are a list of strings where
            each string describes a separate item of clothing. Together they are
            intended to satisfy the full user request.
        recommended_clothes_explanation (list[str]): These are a list of explanations,
            one per clothing item recommended, each of which explains how that clothing
            item satisfies the user's request.
        num_times_critiqued (int): This is the number of times the output of the
            recommendation node has been critiqued. If it exceeds the limit set by
            `cfg.rag_pipeline.max_num_critiques`, then we continue on with the current
            recommendations.
        is_chat_start (bool): This indicates if it is the start of the chat. If it is
            then we don't need to extract anything from the previous interaction, else,
            we need to extract information from previous human interaction.
        recommended_clothes_descriptions (list[str]): List of string descriptions of
            the recommended clothing items. These descriptions are fetched from the
            database rather than generated.
    """

    is_chat_start: bool
    has_input_images: Optional[bool] = Field(default_factory=bool)
    num_times_critiqued: Optional[int] = Field(default_factory=int)
    input_images_path: Optional[list[str]] = Field(default_factory=list)
    input_text: Optional[str] = Field(default_factory=str)
    num_recommendations: Optional[int] = Field(default_factory=int)
    vlm_instructions: Optional[str] = Field(default_factory=str)
    input_images_descriptions: Optional[list[str]] = Field(default_factory=list)
    required_clothes_descriptions: Optional[list[str]] = Field(default_factory=list)
    recommended_clothes_explanation: Optional[list[str]] = Field(default_factory=list)
    recommended_clothes_descriptions: Optional[list[str]] = Field(default_factory=list)
    recommended_clothes_image_paths: Optional[list[str]] = Field(default_factory=list)

