"""The Agentic RAG Pipeline / Graph setup."""

import logging
from typing import Literal, Optional

from langchain.agents import create_agent
from langchain_core.tools import StructuredTool
from langchain_mcp_adapters.client import MultiServerMCPClient
from langgraph.checkpoint.sqlite.aio import AsyncSqliteSaver
from langgraph.graph import END, START, StateGraph
from pydantic import BaseModel, Field

from src.data_manager.vector_db_writer import (
    get_fashion_gen_data,
)
from src.rag_pipeline.llm_schemas import (
    MatchedImageId,
    NumRecommendations,
    RequiredClothes,
    SingleImageDescription,
)
from src.utils.common_utils import (
    draw_langraph_topology,
    get_image_prompt_message,
    get_llm_model,
    track_token_use,
)

log = logging.getLogger(__name__)


def make_mistral_compatible(tool):
    """Wraps an MCP tool to ensure it returns a plain string."""

    def sanitize_response(response):
        result = []
        if isinstance(response, list):
            for block in response:
                if isinstance(block, dict):
                    block_type = block["type"]
                    if block_type == "text":
                        result.append({"type": "text", "text": block["text"]})
                    elif block_type == "image":
                        result.append(
                            {
                                "type": "image_url",
                                "image_url": f"data:{block['mime_type']};base64,{block['base64']}",
                            }
                        )
                    else:
                        raise ValueError("unexpected type")
                else:
                    # we default to converting the whole thing to string if element of
                    # the list is not a dictionary
                    result.append({"type": "text", "text": str(block)})
            return result
        else:
            # we just default to string if response is not a list
            return str(response)

    def sync_wrapper(*args, **kwargs):
        tool_input = args[0] if args else kwargs
        response = tool.invoke(tool_input)
        return sanitize_response(response)

    async def async_wrapper(*args, **kwargs):
        tool_input = args[0] if args else kwargs
        response = await tool.ainvoke(tool_input)
        return sanitize_response(response)

    return StructuredTool.from_function(
        func=sync_wrapper,
        coroutine=async_wrapper,
        name=tool.name,
        description=tool.description,
        args_schema=tool.args_schema,
    )


class AgentState(BaseModel):
    """The stateful component of the agent orchestration in langgraph.

    Attributes:
        has_input_images (bool): Indicates if the user input has any images.
        input_images_path (list[str]): List of string relative paths to the images
            uploaded by the user.
        input_text (str): This is the text part of the user request.
        vlm_instructions (str): This is the description of what the vision language
            model should focus on when analysing the user input image(s). This is
            generated by an LLM, rather than a fixed prompt.
        num_recommendations (int): This is the number of clothing items / accessories
            that the user should be recommended. This can come from the user themselves
            or can be the default value.
        input_images_descriptions (list[str]): These are the descriptions of the user
            supplied images which are obtained from the vision language model. The
            instructions for these are in `vlm_instructions`.
        required_clothes_descriptions (list[str]): These are a list of strings where
            each string describes a separate item of clothing. Together they are
            intended to satisfy the full user request.
        recommended_clothes_images (list[int]): These are a list of indices of the
            clothing items which matched the descriptions in
            `required_clothes_descriptions`.
        recommended_clothes_explanation (list[str]): These are a list of explanations,
            one per clothing item recommended, each of which explains how that clothing
            item satisfies the user's request.
        num_times_critiqued (int): This is the number of times the output of the
            recommendation node has been critiqued. If it exceeds the limit set by
            `cfg.rag_pipeline.max_num_critiques`, then we continue on with the current
            recommendations.
    """

    has_input_images: bool
    num_times_critiqued: int
    input_images_path: list[str]
    input_text: str
    num_recommendations: Optional[int] = Field(default_factory=int)
    vlm_instructions: Optional[str] = Field(default_factory=str)
    input_images_descriptions: Optional[list[str]] = Field(default_factory=list)
    required_clothes_descriptions: Optional[list[str]] = Field(default_factory=list)
    recommended_clothes_images: Optional[list[int]] = Field(default_factory=list)
    recommended_clothes_explanation: Optional[list[str]] = Field(default_factory=list)


class FashionAgent:
    """Constructs and orchestrates the stateful DAG for multimodal retrieval.

    This primary interface initializes the vector database connection, establishes the
    underlying embedding functions, and connects the disparate computational nodes
    (quantification, intent synthesis, visual extraction, modification, and retrieval)
    via LangGraph topologies.

    Args:
        cfg (DictConfig): The hierarchical Hydra configuration object containing
            deterministic parameters for model instantiation, vector database routing,
            and prompt templates.
    """

    def __init__(self, cfg, callback_config):
        """Inits the agentic state representations and external client integrations.

        Instantiates the underlying generative models, the specialized SigLIP embedding
        architecture for multimodal vectorization, and the SQLite-backed vector database
        reader required for semantic similarity operations.

        Args:
            cfg (DictConfig): The Hydra configuration mapping containing systemic
                hyperparameters.
            callback_config (dict): A config object to be used with each llm call in
                order to track the number of input, output, and total tokens used. It
                is useful for Mistral API calls since they are rate limited to 500k
                tokens per minute.
        """
        self._model = get_llm_model(cfg)
        # setup embeddings
        self._cfg = cfg
        self._callback_config = callback_config
        self._client = MultiServerMCPClient(
            {
                "shipping_server": {
                    "transport": "streamable_http",
                    "url": "http://localhost:8000/mcp",
                },
            }
        )

    def quantifier_node(self, state: AgentState) -> AgentState:
        """Figures out how many recommendations need to be made to the user.

        Utilizes the underlying language model to parse the raw textual imperative and
        isolate the explicit numeric quantity requested by the user. If the user omits
        this parameter, the system defaults to a predefined systemic scalar.

        Args:
            state (AgentState): The current multidimensional state vector.

        Returns:
            AgentState: The updated state dictionary containing the
                `num_recommendations` scalar.
        """
        log.debug("Entered quantifier node.")
        prompt = self._cfg.prompts.quantifier_node.num_recommendations_prompt.format(
            user_request=state.input_text
        )
        structured_model = self._model.with_structured_output(NumRecommendations)
        log.debug("Invoking model.")
        response = structured_model.invoke(
            prompt, config=self._callback_config
        )  # text prompt - structured
        log.debug("Received response from model.")
        num_recommendations = (
            self._cfg.rag_pipeline.default_num_recommendations
            if response.num_recommendations == 0
            else response.num_recommendations
        )
        log.debug(
            f"Number of recommendations required by the user:\n{response.num_recommendations}"
        )
        return {"num_recommendations": num_recommendations}

    def intent_node(self, state: AgentState) -> AgentState:
        """Formulates specialized instructions for the downstream visual parsing phase.

        Synthesizes a precise operational directive instructing the Vision Lang Model
        on the specific topological or stylistic features it must extract from the
        multimodal visual matrices.

        Args:
            state (AgentState): The current multidimensional state vector.

        Returns:
            AgentState: The updated state dictionary populated with `vlm_instructions`.
        """
        log.debug("Entered intent node.")
        prompt = self._cfg.prompts.intent_node.request_focus_prompt.format(
            user_request=state.input_text
        )
        log.debug("Invoking model.")
        response = self._model.invoke(
            prompt, config=self._callback_config
        )  # text prompt - unstructured
        log.debug("Received response from model.")
        log.debug(f"Instructions for the VLM:\n{response.content}")
        return {"vlm_instructions": response.content}

    def vision_node(self, state: AgentState) -> AgentState:
        """Executes targeted visual feature extraction across the user-supplied image.

        Iterates sequentially over the provided array of visual inputs, leveraging the
        dynamically synthesized `vlm_instructions` to generate rigorous textual
        representations of the specified features within the images.

        Args:
            state (AgentState): The current multidimensional state vector.

        Returns:
            AgentState: The updated state dictionary appended with
                `input_images_descriptions`.
        """
        log.debug("Entered vision node.")
        structured_model = self._model.with_structured_output(SingleImageDescription)
        descr = []
        for image_path in state.input_images_path:
            msg = get_image_prompt_message(
                image_path=image_path,
                text_prompt=self._cfg.prompts.vision_node.user_prompt.format(
                    image_focus_instructions=state.vlm_instructions
                ),
            )
            log.debug("Invoking model.")
            response = structured_model.invoke(
                msg, config=self._callback_config
            )  # vision prompt - structured
            log.debug("Received response from model.")
            descr.append(response.image_description)
        log.debug(f"Descriptions obtained from vision node:\n{descr}")
        return {"input_images_descriptions": descr}

    def modifier_node(self, state: AgentState) -> AgentState:
        """Produces text descriptions of clothing items requested by user.

        Integrates both the original textual imperative and the newly extracted visual
        feature descriptions to generate an array of target apparel descriptions.
        Implements an iterative retry mechanism to strictly enforce the constraint
        dictated by `num_recommendations`.

        Args:
            state (AgentState): The current multidimensional state vector.

        Returns:
            AgentState: The updated state dictionary containing
                `required_clothes_descriptions`.
        """
        log.debug("Entered modifier node.")
        ref_descr = "\n".join(
            [
                f"{idx + 1}. {img_descr}"
                for idx, img_descr in enumerate(state.input_images_descriptions)
            ]
        )
        if state.has_input_images:
            prompt = self._cfg.prompts.modifier_node.images_present_prompt.format(
                reference_descriptions=ref_descr,
                user_request=state.input_text,
                num_recommendations=state.num_recommendations,
            )
        else:
            prompt = self._cfg.prompts.modifier_node.images_absent_prompt.format(
                user_request=state.input_text,
                num_recommendations=state.num_recommendations,
            )
        structured_model = self._model.with_structured_output(RequiredClothes)
        for attempt_num in range(self._cfg.rag_pipeline.num_recommendation_attempts):
            log.debug("Invoking model.")
            response = structured_model.invoke(
                prompt, config=self._callback_config
            )  # text prompt - structured
            log.debug("Received response from model.")
            if len(response.required_clothes_descriptions) == state.num_recommendations:
                break
            else:
                log.debug(
                    "Failed to get right number of recommendations from LLM after"
                    f"attempt number {attempt_num + 1}."
                )
        log.debug(
            "Required clothes descriptions obtained from modifier node:"
            f"\n{response.required_clothes_descriptions}"
        )
        return {"required_clothes_descriptions": response.required_clothes_descriptions}

    async def recommender_node(self, state: AgentState) -> AgentState:
        """Executes semantic similarity search within the vector embedding space.

        Transforms the target apparel descriptions into dense vector embeddings
        utilizing the SigLIP architecture. Subsequently executes a nearest-neighbor
        search operation across the vector database to extract the highest-scoring
        candidate indices via cosine similarity calculations.

        Args:
            state (AgentState): The current multidimensional state vector.

        Returns:
            AgentState: The updated state dictionary containing a deduplicated set of
                `recommended_clothes_images` indices.
        """
        # clothing items
        recommended_clothes_images = []
        log.debug("Entered recommender node.")
        tools = await self._client.get_tools()
        tools = [make_mistral_compatible(tool) for tool in tools]
        agent = create_agent(
            model=self._model,
            tools=tools,
            response_format=MatchedImageId,
            debug=True,
        )
        template = self._cfg.prompts.recommender_node.match_clothes_prompt
        for descr in state.required_clothes_descriptions:
            prompt = template.format(item_description=descr)
            response = await agent.ainvoke(
                {"messages": prompt}, config=self._callback_config
            )
            recommended_clothes_images.append(response['structured_response'].image_id)
        return {"recommended_clothes_images": recommended_clothes_images}

    def critique_node(self, state: AgentState) -> AgentState:
        """Critiques the recommendations and proposes suggestions.

        Checks if the recommendations are a good response to the user's queries. If
        yes, then we simply move on. If not, it specifically mentions how the
        modifier node should adjust its descriptions of recommended clothes so that
        the next attempt has a better chance of satisfying the users requests. There
        is a limited number of retries after which we continue anyways.

        Args:
            state (AgentState): The current multidimensional state vector.

        Returns:
            AgentState: The updated state dictionary containing the
                `recommended_clothes_explanation` array.
        """
        # This node is not yet for use
        pass

    def explanation_node(self, state: AgentState) -> AgentState:
        """Formulates analytical justifications elucidating the retrieval congruence.

        Correlates the database-retrieved image data with the initial multimodal query,
        tasking the model with producing an explicit, text-based logical defense of how
        the retrieved k elements satisfy the multidimensional input constraints.

        Args:
            state (AgentState): The current multidimensional state vector.

        Returns:
            AgentState: The updated state dictionary containing the
                `recommended_clothes_explanation` array.
        """
        log.debug("Entered explanation node.")
        expl = []
        ref_descr = "\n".join(
            [
                f"{idx + 1}. {img_descr}"
                for idx, img_descr in enumerate(state.input_images_descriptions)
            ]
        )
        descr_key = self._cfg.data.fashion_gen.descriptions_key
        img_key = self._cfg.data.fashion_gen.images_key
        for img_id in state.recommended_clothes_images:
            data = get_fashion_gen_data(self._cfg, from_idx=img_id, to_idx=img_id + 1)
            img_descr = data[descr_key][0]
            if state.has_input_images:
                text_prompt = (
                    self._cfg.prompts.explanation_node.images_present_prompt.format(
                        reference_descriptions=ref_descr,
                        recommended_image_description=img_descr,
                        user_request=state.input_text,
                    )
                )
            else:
                text_prompt = (
                    self._cfg.prompts.explanation_node.images_absent_prompt.format(
                        recommended_image_description=img_descr,
                        user_request=state.input_text,
                    )
                )
            msg = get_image_prompt_message(
                text_prompt=text_prompt, numpy_image=data[img_key][0]
            )
            log.debug("Invoking model.")
            response = self._model.invoke(
                msg, config=self._callback_config
            )  # vision prompt - unstructured
            log.debug("Received response from model.")
            expl.append(response.content)
        log.debug(f"Explanations from explanation_node:\n{expl}")
        return {"recommended_clothes_explanation": expl}

    def quantifier_node_router(
        self, state: AgentState
    ) -> Literal["intent_node", "modifier_node"]:
        """Evaluates conditional branching logic within the LangGraph DAG topology.

        Determines the execution path by inspecting the presence of visual input.
        If images exist, execution is routed to `intent_node`; otherwise, the graph
        bypasses visual processing and directly enters the `modifier_node`.

        Args:
            state (AgentState): The current multidimensional state vector.

        Returns:
            Literal["intent_node", "modifier_node"]: The deterministic string identifier
                of the subsequent vertex in the execution graph.
        """
        return "intent_node" if state.has_input_images else "modifier_node"

    async def ainvoke(self, initial_state, config, conn_string):
        """Compiles the state graph, injects persistence, and initiates execution.

        Constructs the explicit vertex and edge topologies of the RAG pipeline. Attaches
        an SQLite-backed checkpointing protocol for state persistence and executes the
        graph with the designated initial state vector.

        Args:
            initial_state (dict): The dictionary representation of the originating state
                vector.
            config (dict): The configuration dictionary containing metadata such as the
                unique `thread_id`.
            conn_string (str): The persistent Unix-like path or connection URI for the
                SQLite state checkpoint database.

        Returns:
            dict: The final, fully populated state vector at the termination vertex.
        """
        async with AsyncSqliteSaver.from_conn_string(conn_string) as checkpointer:
            builder = StateGraph(AgentState)
            # nodes
            builder.add_node("quantifier_node", self.quantifier_node)
            builder.add_node("intent_node", self.intent_node)
            builder.add_node("vision_node", self.vision_node)
            builder.add_node("modifier_node", self.modifier_node)
            builder.add_node("recommender_node", self.recommender_node)
            builder.add_node("explanation_node", self.explanation_node)
            # edges
            builder.add_edge(START, "quantifier_node")
            builder.add_conditional_edges(
                "quantifier_node", self.quantifier_node_router
            )
            builder.add_edge("intent_node", "vision_node")
            builder.add_edge("vision_node", "modifier_node")
            builder.add_edge("modifier_node", "recommender_node")
            builder.add_edge("recommender_node", "explanation_node")
            builder.add_edge("explanation_node", END)
            # compile and run
            app = builder.compile(checkpointer=checkpointer)
            draw_langraph_topology(app, self._cfg.misc.node_diagram_path)
            invocation_state = (
                None
                if self._cfg.rag_pipeline.persistence.resume_from_checkpoint
                else initial_state
            )
            result = await app.ainvoke(invocation_state, config)
            return result


@track_token_use
async def run_fashion_agent(cfg, callback_config):
    """Instantiates the pipeline environment and triggers agentic execution.

    Operates as the primary entry point for executing the LangGraph agent. It
    initializes the configuration hyperparameters, fabricates a synthetic initialization
    state for validation, constructs the SQLite persistence logic, and invokes the DAG
    traversal.

    Args:
        cfg (DictConfig): The global Hydra configuration object dictating system
            parameters, model weights, and database connections.
    """
    # run fashion agent
    log.debug("Running fashion agent.")
    agent = FashionAgent(cfg, callback_config)
    initial_state = {
        "has_input_images": True,
        "input_images_path": [cfg.misc.input_image_path_01],
        "num_times_critiqued": 0,  # not used
        "input_text": (
            "Please provide 3 jeans pants that will go well with the uploaded shirt."
        ),
    }
    config = {"configurable": {"thread_id": cfg.rag_pipeline.persistence.thread_id}}
    result = await agent.ainvoke(initial_state, config, cfg.rag_pipeline.persistence.db_path)
    log.debug(f"Result: {result}")
