"""The Agentic RAG Pipeline / Graph setup."""

import logging
from typing import Literal, Optional

import hydra
from langgraph.checkpoint.sqlite import SqliteSaver
from langgraph.graph import END, START, StateGraph
from pydantic import BaseModel, Field

from src.data_manager.vector_db_reader import VectorDbReader
from src.data_manager.vector_db_writer import (
    FashionSigLIPEmbedding,
    get_fashion_gen_data,
)
from src.rag_pipeline.llm_schemas import (
    NumRecommendations,
    RequiredClothes,
    SingleImageDescription,
)
from src.utils.common_utils import (
    draw_langraph_topology,
    get_categories_from_string,
    get_image_prompt_message,
)

log = logging.getLogger(__name__)


class AgentState(BaseModel):
    """The stateful component of the agent orchestration in langgraph.

    Attributes:
        has_input_images (bool): Indicates if the user input has any images.
        input_images_path (list[str]): List of string relative paths to the images
            uploaded by the user.
        input_text (str): This is the text part of the user request.
        vlm_instructions (str): This is the description of what the vision language
            model should focus on when analysing the user input image(s). This is
            generated by an LLM, rather than a fixed prompt.
        num_recommendations (int): This is the number of clothing items / accessories
            that the user should be recommended. This can come from the user themselves
            or can be the default value.
        input_images_descriptions (list[str]): These are the descriptions of the user
            supplied images which are obtained from the vision language model. The
            instructions for these are in `vlm_instructions`.
        required_clothes_descriptions (list[str]): These are a list of strings where
            each string describes a separate item of clothing. Together they are
            intended to satisfy the full user request.
        recommended_clothes_images (list[int]): These are a list of indices of the
            clothing items which matched the descriptions in
            `required_clothes_descriptions`.
        recommended_clothes_explanation (list[str]): These are a list of explanations,
            one per clothing item recommended, each of which explains how that clothing
            item satisfies the user's request.
        required_clothes_categories (list[str]): This is a list of categories to which
            each of the recommended descriptions belongs. This will help filter the
            search in qdrant vector matching.
    """

    has_input_images: bool
    input_images_path: list[str]
    input_text: str
    num_recommendations: Optional[int] = Field(default_factory=int)
    vlm_instructions: Optional[str] = Field(default_factory=str)
    input_images_descriptions: Optional[list[str]] = Field(default_factory=list)
    required_clothes_descriptions: Optional[list[str]] = Field(default_factory=list)
    required_clothes_categories: Optional[list[list[str]]] = Field(default_factory=list)
    recommended_clothes_images: Optional[list[int]] = Field(default_factory=list)
    recommended_clothes_explanation: Optional[list[str]] = Field(default_factory=list)


class FashionAgent:
    """Constructs and orchestrates the stateful DAG for multimodal retrieval.

    This primary interface initializes the vector database connection, establishes the
    underlying embedding functions, and connects the disparate computational nodes
    (quantification, intent synthesis, visual extraction, modification, and retrieval)
    via LangGraph topologies.

    Args:
        cfg (DictConfig): The hierarchical Hydra configuration object containing
            deterministic parameters for model instantiation, vector database routing,
            and prompt templates.
    """

    def __init__(self, cfg):
        """Inits the agentic state representations and external client integrations.

        Instantiates the underlying generative models, the specialized SigLIP embedding
        architecture for multimodal vectorization, and the SQLite-backed vector database
        reader required for semantic similarity operations.

        Args:
            cfg (DictConfig): The Hydra configuration mapping containing systemic
                hyperparameters.
        """
        provider = hydra.utils.instantiate(cfg.models.vlm_agent)
        self._model = provider(
            model=cfg.models.vlm_agent.name,
            temperature=cfg.models.vlm_agent.temp,
        )
        self._embedder = FashionSigLIPEmbedding(cfg)
        self._reader = VectorDbReader(cfg)
        self._cfg = cfg

    def quantifier_node(self, state: AgentState) -> AgentState:
        """Figures out how many recommendations need to be made to the user.

        Utilizes the underlying language model to parse the raw textual imperative and
        isolate the explicit numeric quantity requested by the user. If the user omits
        this parameter, the system defaults to a predefined systemic scalar.

        Args:
            state (AgentState): The current multidimensional state vector.

        Returns:
            AgentState: The updated state dictionary containing the
                `num_recommendations` scalar.
        """
        log.debug("Entered recommendations node.")
        prompt = self._cfg.prompts.quantifier_node.num_recommendations_prompt.format(
            user_request=state.input_text
        )
        structured_model = self._model.with_structured_output(NumRecommendations)
        log.debug("Invoking model.")
        response = structured_model.invoke(prompt)  # text prompt - structured
        log.debug("Received response from model.")
        num_recommendations = (
            self._cfg.rag_pipeline.default_num_recommendations
            if response.num_recommendations == 0
            else response.num_recommendations
        )
        log.debug(
            f"Number of recommendations from the user:\n{response.num_recommendations}"
        )
        return {"num_recommendations": num_recommendations}

    def intent_node(self, state: AgentState) -> AgentState:
        """Formulates specialized instructions for the downstream visual parsing phase.

        Synthesizes a precise operational directive instructing the Vision Lang Model
        on the specific topological or stylistic features it must extract from the
        multimodal visual matrices.

        Args:
            state (AgentState): The current multidimensional state vector.

        Returns:
            AgentState: The updated state dictionary populated with `vlm_instructions`.
        """
        log.debug("Entered intent node.")
        prompt = self._cfg.prompts.intent_node.request_focus_prompt.format(
            user_request=state.input_text
        )
        log.debug("Invoking model.")
        response = self._model.invoke(prompt)  # text prompt - unstructured
        log.debug("Received response from model.")
        log.debug(f"Instructions for the VLM:\n{response.content}")
        return {"vlm_instructions": response.content}

    def vision_node(self, state: AgentState) -> AgentState:
        """Executes targeted visual feature extraction across the user-supplied image.

        Iterates sequentially over the provided array of visual inputs, leveraging the
        dynamically synthesized `vlm_instructions` to generate rigorous textual
        representations of the specified features within the images.

        Args:
            state (AgentState): The current multidimensional state vector.

        Returns:
            AgentState: The updated state dictionary appended with
                `input_images_descriptions`.
        """
        log.debug("Entered vision node.")
        structured_model = self._model.with_structured_output(SingleImageDescription)
        descr = []
        for image_path in state.input_images_path:
            msg = get_image_prompt_message(
                image_path=image_path,
                text_prompt=self._cfg.prompts.vision_node.user_prompt.format(
                    image_focus_instructions=state.vlm_instructions
                ),
            )
            log.debug("Invoking model.")
            response = structured_model.invoke(msg)  # vision prompt - structured
            log.debug("Received response from model.")
            descr.append(response.image_description)
        log.debug(f"Descriptions obtained from vision node:\n{descr}")
        return {"input_images_descriptions": descr}

    def modifier_node(self, state: AgentState) -> AgentState:
        """Produces text descriptions of clothing items requested by user.

        Integrates both the original textual imperative and the newly extracted visual
        feature descriptions to generate an array of target apparel descriptions.
        Implements an iterative retry mechanism to strictly enforce the constraint
        dictated by `num_recommendations`.

        Args:
            state (AgentState): The current multidimensional state vector.

        Returns:
            AgentState: The updated state dictionary containing
                `required_clothes_descriptions`.
        """
        log.debug("Entered modifier node.")
        ref_descr = "\n".join(
            [
                f"{idx + 1}. {img_descr}"
                for idx, img_descr in enumerate(state.input_images_descriptions)
            ]
        )
        if state.has_input_images:
            prompt = self._cfg.prompts.modifier_node.images_present_prompt.format(
                reference_descriptions=ref_descr,
                user_request=state.input_text,
                num_recommendations=state.num_recommendations,
            )
        else:
            prompt = self._cfg.prompts.modifier_node.images_absent_prompt.format(
                user_request=state.input_text,
                num_recommendations=state.num_recommendations,
            )
        structured_model = self._model.with_structured_output(RequiredClothes)
        for attempt_num in range(self._cfg.rag_pipeline.num_recommendation_attempts):
            log.debug("Invoking model.")
            response = structured_model.invoke(prompt)  # text prompt - structured
            log.debug("Received response from model.")
            if len(response.required_clothes_descriptions) == state.num_recommendations:
                break
            else:
                log.debug(
                    "Failed to get right number of recommendations from LLM after"
                    f"attempt number {attempt_num + 1}."
                )
        log.debug(
            "Required clothes descriptions obtained from modifier node:"
            f"\n{response.required_clothes_descriptions}"
        )
        return {"required_clothes_descriptions": response.required_clothes_descriptions}

    def filtration_node(self, state: AgentState) -> AgentState:
        """Gets the filters for the required clothes descriptions.

        Each item in the dataset or product catalogue being used belongs to one
        category. When searching the vector database for product items that match
        the required_clothes_descriptions, the recommendations become more appropriate
        when they are filtered based on the category to which each requirement belongs.
        This node invokes the LLM for each description and asks the LLM to choose which
        category the item being described belongs to. Each description might belong to
        more than one category.

        Args:
            state (AgentState): The current multidimensional state vector.

        Returns:
            AgentState: The updated state dictionary containing a list of list of
                categories in `required_clothes_categories` key.
        """
        log.debug("Entered filtration node.")
        valid_categories = (
            "['" + "', '".join(self._cfg.data.fashion_gen.product_categories) + "']"
        )
        # structured_model = self._model.with_structured_output(ValidCategories)
        categories = []
        for descr in state.required_clothes_descriptions:
            prompt = self._cfg.prompts.filtration_node.category_choice_prompt.format(
                valid_categories=valid_categories, item_description=descr
            )
            log.debug("Invoking model.")
            response = self._model.invoke(prompt)  # text prompt - unstructured
            log.debug("Received response from model.")
            categories.append(get_categories_from_string(self._cfg, response.content))
        log.debug(f"Categories of descriptions:\n{categories}")
        return {"required_clothes_categories": categories}

    def recommender_node(self, state: AgentState) -> AgentState:
        """Executes semantic similarity search within the vector embedding space.

        Transforms the target apparel descriptions into dense vector embeddings
        utilizing the SigLIP architecture. Subsequently executes a nearest-neighbor
        search operation across the vector database to extract the highest-scoring
        candidate indices via cosine similarity calculations.

        Args:
            state (AgentState): The current multidimensional state vector.

        Returns:
            AgentState: The updated state dictionary containing a deduplicated set of
                `recommended_clothes_images` indices.
        """
        # TODO: figure out a way to ensure that you stick to the number of required
        # clothing items
        log.debug("Entered recommender node.")
        # get embeddings for each of the required clothes descriptions
        # get the top image match for each of the embeddings - need client for this
        # populate the recommended_clothes_images with the indexes of the returned
        # matches
        match_ids = []
        embeddings = self._embedder.get_text_embedding_batch(
            state.required_clothes_descriptions
        )
        for idx, embedding in enumerate(embeddings):
            match_ids.extend(
                self._reader.get_image_matches(
                    embedding,
                    num_matches=1,
                    categories=state.required_clothes_categories[idx],
                )
            )
        log.debug(f"Image IDs obtained from recommender_node:\n{match_ids}")
        return {"recommended_clothes_images": set(list(match_ids))}

    def explanation_node(self, state: AgentState) -> AgentState:
        """Formulates analytical justifications elucidating the retrieval congruence.

        Correlates the database-retrieved image data with the initial multimodal query,
        tasking the model with producing an explicit, text-based logical defense of how
        the retrieved k elements satisfy the multidimensional input constraints.

        Args:
            state (AgentState): The current multidimensional state vector.

        Returns:
            AgentState: The updated state dictionary containing the
                `recommended_clothes_explanation` array.
        """
        log.debug("Entered explanation node.")
        expl = []
        ref_descr = "\n".join(
            [
                f"{idx + 1}. {img_descr}"
                for idx, img_descr in enumerate(state.input_images_descriptions)
            ]
        )
        descr_key = self._cfg.data.fashion_gen.descriptions_key
        img_key = self._cfg.data.fashion_gen.images_key
        for img_id in state.recommended_clothes_images:
            data, done = get_fashion_gen_data(
                self._cfg, from_idx=img_id, to_idx=img_id + 1
            )
            img_descr = data[descr_key][0]
            if state.has_input_images:
                text_prompt = (
                    self._cfg.prompts.explanation_node.images_present_prompt.format(
                        reference_descriptions=ref_descr,
                        recommended_image_description=img_descr,
                        user_request=state.input_text,
                    )
                )
            else:
                text_prompt = (
                    self._cfg.prompts.explanation_node.images_absent_prompt.format(
                        recommended_image_description=img_descr,
                        user_request=state.input_text,
                    )
                )
            msg = get_image_prompt_message(
                text_prompt=text_prompt, numpy_image=data[img_key][0]
            )
            log.debug("Invoking model.")
            response = self._model.invoke(msg)  # vision prompt - unstructured
            log.debug("Received response from model.")
            expl.append(response.content)
        log.debug(f"Explanations from explanation_node:\n{expl}")
        return {"recommended_clothes_explanation": expl}

    def quantifier_node_router(
        self, state: AgentState
    ) -> Literal["intent_node", "modifier_node"]:
        """Evaluates conditional branching logic within the LangGraph DAG topology.

        Determines the execution path by inspecting the presence of visual input.
        If images exist, execution is routed to `intent_node`; otherwise, the graph
        bypasses visual processing and directly enters the `modifier_node`.

        Args:
            state (AgentState): The current multidimensional state vector.

        Returns:
            Literal["intent_node", "modifier_node"]: The deterministic string identifier
                of the subsequent vertex in the execution graph.
        """
        return "intent_node" if state.has_input_images else "modifier_node"

    def invoke(self, initial_state, config, conn_string):
        """Compiles the state graph, injects persistence, and initiates execution.

        Constructs the explicit vertex and edge topologies of the RAG pipeline. Attaches
        an SQLite-backed checkpointing protocol for state persistence and executes the
        graph with the designated initial state vector.

        Args:
            initial_state (dict): The dictionary representation of the originating state
                vector.
            config (dict): The configuration dictionary containing metadata such as the
                unique `thread_id`.
            conn_string (str): The persistent Unix-like path or connection URI for the
                SQLite state checkpoint database.

        Returns:
            dict: The final, fully populated state vector at the termination vertex.
        """
        with SqliteSaver.from_conn_string(conn_string) as checkpointer:
            builder = StateGraph(AgentState)
            # nodes
            builder.add_node("quantifier_node", self.quantifier_node)
            builder.add_node("intent_node", self.intent_node)
            builder.add_node("vision_node", self.vision_node)
            builder.add_node("modifier_node", self.modifier_node)
            builder.add_node("recommender_node", self.recommender_node)
            builder.add_node("explanation_node", self.explanation_node)
            builder.add_node("filtration_node", self.filtration_node)
            # edges
            builder.add_edge(START, "quantifier_node")
            builder.add_conditional_edges(
                "quantifier_node", self.quantifier_node_router
            )
            builder.add_edge("intent_node", "vision_node")
            builder.add_edge("vision_node", "modifier_node")
            builder.add_edge("modifier_node", "filtration_node")
            builder.add_edge("filtration_node", "recommender_node")
            builder.add_edge("recommender_node", "explanation_node")
            builder.add_edge("explanation_node", END)
            # compile and run
            app = builder.compile(checkpointer=checkpointer)
            draw_langraph_topology(app, self._cfg.misc.node_diagram_path)
            invocation_state = (
                None
                if self._cfg.rag_pipeline.persistence.resume_from_checkpoint
                else initial_state
            )
            result = app.invoke(invocation_state, config)
            return result


def run_fashion_agent(cfg):
    """Instantiates the pipeline environment and triggers agentic execution.

    Operates as the primary entry point for executing the LangGraph agent. It
    initializes the configuration hyperparameters, fabricates a synthetic initialization
    state for validation, constructs the SQLite persistence logic, and invokes the DAG
    traversal.

    Args:
        cfg (DictConfig): The global Hydra configuration object dictating system
            parameters, model weights, and database connections.
    """
    log.debug("Running fashion agent.")
    agent = FashionAgent(cfg)
    initial_state = {
        "has_input_images": True,
        "input_images_path": [cfg.misc.input_image_path_01],
        "input_text": (
            "Please provide 3 jeans pants that will go well with the uploaded shirt."
        ),
    }
    config = {"configurable": {"thread_id": cfg.rag_pipeline.persistence.thread_id}}
    result = agent.invoke(initial_state, config, cfg.rag_pipeline.persistence.db_path)
    log.debug(f"Result: {result}")
