persistence:
  # this defines what checkpointer backend to use - postgres or sqlite
  backend: postgres
  sqlite:
    # this is the sqlite db used for checkpoint persistence
    db_path: data/pipeline_checkpoints.db
  postgres:
    # this is the connection string used for postgres
    db_connection_string: postgresql://${oc.env:POSTGRES_USER}:${oc.env:POSTGRES_PASSWORD}@localhost:5432/${oc.env:POSTGRES_DB}
    # max simultaneous connections - this is for the postgres connection pool
    max_pool_size: 20

# TODO: put this under some sub-heading
# this is to determine the number of recommendations to return to the user if the user does not specify how many recommendations they want
default_num_recommendations: 3

# this is how many times we will try to generate the correct number of recommendations - in the modifier node
num_recommendation_attempts: 3

# this is the maximum number of times the critique node is allowed to critique the output of the recommendation node
max_num_critiques: 3

mcp:
  llm_tool_names:
    - semantic_search
    - get_product_categories
  db_tool_name: get_datapoint_by_index

# this is where the images fetched from the fashion gen database for evaluation are stored. the folder is deleted at the end when running the app, but not deleted when running the cli_main.py file
temporary_images_folder: data/temp_images/

# this is where the agent's langgraph orchestration diagram is stored
node_diagram_path: fashion_agent_diagram.png
