defaults:
  - models: models_01
  - data: data_01
  - prompts: prompts_01
  - misc: misc_01
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog


hydra:
  verbose:
    - __main__
    - src.data_manager.vector_db_writer
    - src.exploration.langgraph_exploration
    - src.exploration.data_exploration
