defaults:
  - models: models_01
  - data: data_01
  - prompts: prompts_01
  - rag_pipeline: rag_pipeline_01
  - misc: misc_01
  - tracking: tracking_01
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog


hydra:
  verbose:
    - __main__
    - src.data_manager.vector_db_writer
    - src.data_manager.vector_db_reader
    - src.utils.common_utils
    - src.rag_pipeline.rag_agent
    - src.mcp_server.mcp_client
    # exploration
    - src.exploration.mistral_exploration
    - src.exploration.langgraph_exploration
    - src.exploration.data_exploration
    - src.exploration.fast_mcp_exploration.shipping_agent_client
    - src.exploration.fast_mcp_exploration.shipping_agent_server
