# this file was generated by claude code - to automatically use my current config object, convert to yaml for my review, then upload to aws parameter store
"""
ssm_sync.py — Upload a Pydantic config object to AWS SSM Parameter Store.

Workflow
--------
Step 1 — Generate a plan file you can review:
    uv run -m frag.utils.aws_ssm_sync plan

Step 2 — Inspect ssm_plan.yaml, adjust 'type' / 'skip' fields if needed.
Add any variables to skip or put secret in frag.config.aws_parameter_store.py file

Step 3 — Apply the reviewed plan:
    uv run -m frag.utils.aws_ssm_sync apply

Shortcut (generate + apply without manual review):
    uv run -m frag.utils.aws_ssm_sync plan --apply

Dry-run (simulate upload, print what *would* happen):
    uv run -m frag.utils.aws_ssm_sync apply --dry-run
"""

import json
import argparse
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import boto3
import yaml
from botocore.exceptions import ClientError
from loguru import logger as log
from dependency_injector.wiring import inject, Provide as PV

# construct the wiring
from frag.config.container import Container

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

@inject
def _flatten(
    data: dict[str, Any],
    parent: str = "",
    delimiter: str = PV[Container.config.provided.aws_param_store.env_nested_delimiter],
) -> dict[str, Any]:
    """
    Recursively flatten a nested dict (from model.model_dump()).

    Nesting strategy
    ----------------
    Nested keys are joined with `delimiter` (default '__').  This matches
    pydantic-settings' env_nested_delimiter so BaseSettings resolves them
    automatically: DATABASE__HOST → settings.database.host.

    Type handling
    -------------
    • dict  → recurse (nested BaseModel)
    • list  → JSON-encode ("['a','b']"), pydantic v2 parses this from env
    • None  → skip (field is unset / optional with no default)
    • other → str()
    """
    result: dict[str, Any] = {}
    for key, value in data.items():
        full_key = f"{parent}{delimiter}{key}" if parent else key
        if isinstance(value, dict):
            result.update(_flatten(value, full_key))
        elif value is None:
            pass
        elif isinstance(value, list):
            result[full_key] = json.dumps(value)
        else:
            result[full_key] = str(value)
    return result


# ---------------------------------------------------------------------------
# Core: Pydantic model → SSM parameter descriptors
# ---------------------------------------------------------------------------

@inject
def config_to_ssm_params(
    config, ssm_prefix, delimiter,
    skip_configs: list[str] = PV[Container.config.provided.aws_param_store.skip_configs],
    secure_string_configs: list[str] = PV[Container.config.provided.aws_param_store.secure_string_configs],
) -> list[dict]:
    """
    Flatten a (nested) Pydantic model into SSM parameter descriptors.

    Returns a list of dicts, each representing one SSM parameter:
        {
            "name":         "/fashion-agent/database__host",
            "value":        "localhost",
            "type":         "String",          # or "SecureString"
            "overwrite":    True,
            "skip":         False,             # set True in the plan to exclude
            "source_field": "database__host",  # traceability
        }
    """
    flat = _flatten(config.model_dump())
    prefix = ssm_prefix.rstrip("/")

    params = []
    for field_key, value in flat.items():
        ssm_name = f"{prefix}/{field_key.lower()}"
        params.append(
            {
                "name": ssm_name,
                "value": value,
                "type": "SecureString" if field_key in secure_string_configs else "String",
                "overwrite": True,
                "skip": True if field_key in skip_configs else False,
                "source_field": field_key,
            }
        )
    return sorted(params, key=lambda p: p["name"])


# ---------------------------------------------------------------------------
# Plan: generate YAML
# ---------------------------------------------------------------------------

def generate_plan(
    ssm_prefix, plan_file,
    config = PV[Container.config.provided],
    delimiter: str = PV[Container.config.provided.aws_param_store.env_nested_delimiter],
) -> list[dict]:
    """Write a human-reviewable YAML plan and return the param list."""
    log.debug('generating a plan')
    params = config_to_ssm_params(config, ssm_prefix=ssm_prefix, delimiter=delimiter)
    log.debug('got the params')

    n_secure = sum(1 for p in params if p["type"] == "SecureString")
    n_plain = len(params) - n_secure

    plan = {
        # ------------------------------------------------------------------
        # meta block: informational only, not used by apply_plan
        # ------------------------------------------------------------------
        "meta": {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "ssm_prefix": ssm_prefix,
            "env_nested_delimiter": delimiter,
            "total_parameters": len(params),
            "secure_string_count": n_secure,
            "string_count": n_plain,
            "instructions": (
                "Review each parameter below. "
                "You may change 'type' (String/SecureString) or set 'skip: true' "
                "to exclude a parameter from the upload. "
                "Do NOT commit this file — it contains plaintext secrets."
            ),
        },
        "parameters": params,
    }

    out = Path(plan_file)
    with out.open("w") as f:
        yaml.dump(plan, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

    log.debug(f"\n✅  Plan written → {out.resolve()}")
    log.debug(f"   {len(params)} parameters total")
    log.debug(f"   {n_secure:>3} SecureString  (auto-detected sensitive fields)")
    log.debug(f"   {n_plain:>3} String")
    log.debug(
        "\n⚠️  Review the plan file before applying — "
        "it contains plaintext values including secrets.\n"
    )
    return params


def apply_plan(
    plan_file: str,
    region: str,
    dry_run: bool = False,
) -> None:
    """Read the plan YAML and upload each parameter to SSM Parameter Store."""
    plan_path = Path(plan_file)
    if not plan_path.exists():
        sys.exit(f"Plan file not found: {plan_path}. Run `plan` first.")

    with plan_path.open() as f:
        plan = yaml.safe_load(f)

    params: list[dict] = plan["parameters"]
    total = len(params)
    skipped_flag = sum(1 for p in params if p.get("skip"))
    to_upload = [p for p in params if not p.get("skip")]

    log.debug(
        f"{'[DRY RUN] ' if dry_run else ''}"
        f"Uploading {len(to_upload)}/{total} parameters "
        f"({skipped_flag} skipped via 'skip: true') "
        f"→ region {region}"
    )

    if not dry_run:
        ssm = boto3.client("ssm", region_name=region)

    ok = failed = 0
    for p in to_upload:
        if dry_run:
            masked = "***" if p["type"] == "SecureString" else p["value"]
            log.debug(f"  [dry-run] {p['name']}  ({p['type']})  = {masked!r}")
            ok += 1
            continue

        try:
            ssm.put_parameter(
                Name=p["name"],
                Value=p["value"],
                Type=p["type"],
                Overwrite=p.get("overwrite", True),
            )
            log.debug(f"  ✓  {p['name']}  ({p['type']})")
            ok += 1
        except ClientError as exc:
            code = exc.response["Error"]["Code"]
            msg = exc.response["Error"]["Message"]
            log.debug(f"  ✗  {p['name']}  → {code}: {msg}", file=sys.stderr)
            failed += 1

    log.debug(f"\n{'[DRY RUN] ' if dry_run else ''}Done: {ok} uploaded, {failed} failed.")
    if failed:
        sys.exit(1)
# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

@inject
def _build_parser(
    default_ssm_prefix: str = PV[Container.config.provided.aws_param_store.default_ssm_prefix],
    default_plan_file: str = PV[Container.config.provided.aws_param_store.default_plan_file],
    default_region: str = PV[Container.config.provided.aws_param_store.default_region],
) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Sync a Pydantic config object to AWS SSM Parameter Store.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    sub = parser.add_subparsers(dest="cmd", required=True)

    # plan sub-command
    p_plan = sub.add_parser("plan", help="Generate ssm_plan.yaml from your config")
    p_plan.add_argument(
        "--prefix", default=default_ssm_prefix,
        help=f"SSM path prefix (default: {default_ssm_prefix!r})",
    )
    p_plan.add_argument(
        "--out", default=default_plan_file,
        help=f"Output file path (default: {default_plan_file!r})",
    )
    p_plan.add_argument(
        "--apply", action="store_true",
        help="Apply the plan immediately after generating it (skips manual review step)",
    )
    p_plan.add_argument(
        "--region", default=default_region,
        help=f"AWS region (only used when --apply is set; default: {default_region!r})",
    )

    # apply sub-command
    p_apply = sub.add_parser("apply", help="Upload a reviewed ssm_plan.yaml to AWS")
    p_apply.add_argument(
        "--plan", default=default_plan_file,
        help=f"Plan file to apply (default: {default_plan_file!r})",
    )
    p_apply.add_argument(
        "--region", default=default_region,
        help=f"AWS region (default: {default_region!r})",
    )
    p_apply.add_argument(
        "--dry-run", action="store_true",
        help="Print what would be uploaded without actually calling SSM",
    )

    return parser


@log.catch
def main() -> None:
    log.debug('in the main function')
    parser = _build_parser()
    args = parser.parse_args()
    log.debug('built the parser and got the args')

    if args.cmd == "plan":
        generate_plan(ssm_prefix=args.prefix, plan_file=args.out)
        if args.apply:
            apply_plan(plan_file=args.out, region=args.region)
    elif args.cmd == "apply":
        apply_plan(plan_file=args.plan, region=args.region, dry_run=args.dry_run)



if __name__ == "__main__":
    container = Container()
    # we need this call explicitly here (after everything is defined), since this is a standalone file.
    container.wire(modules=["__main__"])

    log.debug("cfg = {}", Container.config.provided)
    main()
