# This file is meant to be run on an EC2 instance and is thus standalone
# the purpose is to connect to a running Qdrant Container, generate embeddings
# of images and text and then insert them into the vector db on an attached
# EBS instance.

import io
import json
import asyncio
import logging as log

import boto3
import pyarrow.parquet as pq
from qdrant_client import AsyncQdrantClient, models


log.basicConfig(
    level=log.DEBUG,
    format="%(asctime)s - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)

# globals
# for setting up qdrant client
# this is the url location of the qdrant docker client - this can't actually be an http url since the actual value expected in the receiver is str and it throws an error if I set it as HttpUrl
vector_db_url = "http://localhost:6333"

# qdrant allows two api's - rest and grpc. grpc is more performant while rest api is more convenient. the docs recommend using grpc if we are already familiar with qdrant and are trying to optimize the performance of our application.
prefer_grpc = True

# this flag controls if the collection is recreated if it already exists. This will remain true while I have not generated the full collection, so that it starts from the beginning each time - clean create
recreate = True

# this is the name of the collection in qdrant
collection_name = "fashion_gen"

# when inserting the embeddings in to qdrant, since they are multi-modal, I am inserting them as named vectors. Below 2 are the names.
image_vectors_name = "images"
text_vectors_name = "texts"

# this is the dimensionality of the embedding generated by amazon nova model
embedding_size = 1024

# this flag controls whether or not we use Memory Map storage in qdrant (also called on-disk storage) from the start - which is recommended for large collections
vectors_on_disk = True

# this flag controls if we write the payload onto the disk or keep it in memory (RAM)
payload_on_disk = True

# this flag control if we move the Hnsw graph onto the disk or not
hnsw_on_disk = True

# this value controls the number of vectors after which we start building HNSW graphs (20k is default)
# Setting it to 0 disables HNSW indexing entirely during the bulk load, which dramatically speeds up ingestion; after all points are loaded, update the collection config to restore it and let Qdrant build the index in one pass
indexing_threshold = 0
final_indexing_threshold = 20_000

# this is the qdrant client - populated in setup_qdrant_client
qdrant_client = None

# the name of the bucket in which the images of the fashion gen dataset are stored, and where the metadata is stored
data_bucket_name: str = 'frag-fashion-gen-dataset'

# this function gives the s3 key given a fashion gen image index corresponding to the location where the image is stored in s3
get_image_s3_key_from_index = lambda idx: f"images/{idx // 1000:03d}/{idx}.png"

# this is the aws s3 account id
account_id = "650539477368"

# this is the model to use to generate the embeddings
model_id = "amazon.nova-2-multimodal-embeddings-v1:0"

# the s3 key for the metadata file
metadata_key = "metadata/fashion_gen_metadata.parquet"

# this is the dictionary containing all the metadata for the fashion gen images.
# it can be accessed by doing metadata_lookup[index][key] if you want to lookup some key like "input_description"
metadata_lookup = None

# this is the value of the key we can use to extract descriptions of images
descriptions_key = "input_description"

# this is the instance of the class which generates (using amazon aws nova) the embeddings and returns them
embedder = None

# this is the total number of datapoints present in the fashion-gen dataset
num_datapoints = 260_490

# these are the attributes from the metadata that we want to capture in the vector db metadata
payload_attributes = [
    "s3_keys",
    "index_2",
    "input_msrpUSD",
    "input_brand",
    "input_category",
    "input_composition",
    "input_department",
    "input_gender",
    "input_name",
    "input_season",
    "input_subcategory",
    "input_description",
]

# this is the key in metadata_lookup that holds the index of the image
index_key = "index_2"

# this is the number of datapoints we fetch at one time from the fashion-gen dataset. Best for it to be some integer multiple of the batch size. Not so large that it does not fit in RAM. Without writing image to payload, the process is really fast.
fetch_batch_size: int = 256

# this is the value to which the semaphore controlling how many simultaneous queries can be made to aws bedrock, is set
aws_bedrock_simultaneous_queries = 20

async def setup_qdrant_client():
    """Create the vector db client,and collection, and returns the client.

    Depending on the setup the existing collection might be deleted and a new
    collection created. Or if the collection already exists and the recreate flag is
    not enabled, then the existing collection is fetched.
    """
    global vector_db_url, prefer_grpc, recreate, collection_name, image_vectors_name, text_vectors_name, embedding_size, vectors_on_disk, payload_on_disk, hnsw_on_disk, indexing_threshold, qdrant_client

    qdrant_client = AsyncQdrantClient(url=vector_db_url, prefer_grpc=prefer_grpc)

    if recreate and await qdrant_client.collection_exists(collection_name):
        await qdrant_client.delete_collection(collection_name)
        log.info(f"Deleted existing collection '{collection_name}'.")

    if not await qdrant_client.collection_exists(collection_name):
        await qdrant_client.create_collection(
            collection_name=collection_name,
            vectors_config={
                image_vectors_name: models.VectorParams(
                    size=embedding_size,
                    distance=models.Distance.DOT,
                    on_disk=vectors_on_disk,
                ),
                text_vectors_name: models.VectorParams(
                    size=embedding_size,
                    distance=models.Distance.COSINE,
                    on_disk=vectors_on_disk,
                ),
            },
            on_disk_payload=payload_on_disk,
            optimizers_config=models.OptimizersConfigDiff(
                indexing_threshold=indexing_threshold,
            ),
            hnsw_config=models.HnswConfigDiff(on_disk=hnsw_on_disk),
        )
        log.info(f"Created new collection '{collection_name}'...")
    else:
        log.info(f"Collection '{collection_name}' already exists. Appending.")

async def setup_metadata_lookup():
    global data_bucket_name, metadata_key, metadata_lookup

    s3_client = boto3.client("s3")
    log.debug("setting up metadata lookup")
    buffer = io.BytesIO()
    await asyncio.to_thread(s3_client.download_fileobj, data_bucket_name, metadata_key, buffer)
    buffer.seek(0)
    # read with pyarrow
    table = pq.read_table(buffer)
    df = table.to_pandas()
    metadata_lookup = df.to_dict(orient='index')

class Embedder():
    def __init__(self):
        self.client = boto3.client("bedrock-runtime")
        self._sem = None

    def _get_text_request_body(self, index):
        global embedding_size, metadata_lookup, descriptions_key

        description = metadata_lookup[index][descriptions_key]
        request_body = {
            "taskType": "SINGLE_EMBEDDING",
            "singleEmbeddingParams": {
                "embeddingPurpose": "GENERIC_INDEX",
                "embeddingDimension": embedding_size,
                "text": {
                    "value": description,
                    "truncationMode": "END"
                }
            }
        }
        return request_body

    def _get_image_request_body(self, index):
        global data_bucket_name, get_image_s3_key_from_index, account_id, embedding_size

        image_s3_uri  = f"s3://{data_bucket_name}/{get_image_s3_key_from_index(index)}"
        request_body = {
            "taskType": "SINGLE_EMBEDDING",
            "singleEmbeddingParams": {
                "embeddingPurpose": "GENERIC_INDEX",
                "embeddingDimension": embedding_size,
                "image": {
                    "detailLevel": "STANDARD_IMAGE",
                    "format": "png",
                    "source": {
                        "s3Location": {
                            "uri": image_s3_uri,
                            "bucketOwner": account_id
                        }
                    }
                }
            }
        }
        return request_body

    def _get_embedding(self, request_body):
        global model_id

        try:
            response = self.client.invoke_model(
                body=json.dumps(request_body),
                modelId=model_id,
                accept="application/json",
                contentType="application/json",
            )
        except Exception as e:
            log.exception("There was an exception while getting embedding of an image on s3.")
            raise

        resp_body = json.loads(response["body"].read())
        embedding = resp_body["embeddings"][0]["embedding"]
        return embedding

    def _get_text_embedding(self, index):
        return self._get_embedding(self._get_text_request_body(index))

    def _get_image_embedding(self, index):
        return self._get_embedding(self._get_image_request_body(index))

    async def get_text_embedding(self, index):
        return await asyncio.to_thread(self._get_text_embedding, index)

    async def get_image_embedding(self, index):
        return await asyncio.to_thread(self._get_image_embedding, index)

    async def _get_single_paired_embedding(self, index):
        async with self._sem:
            image_vector, text_vector = await asyncio.gather(
                self._get_image_embedding(index),
                self._get_text_embedding(index),
            )
        return image_vector, text_vector

    async def get_paired_embedding_batch(self, from_idx, to_idx):
        global aws_bedrock_simultaneous_queries
        if self._sem is None:
            # we divide by two since we are making two queries within the semaphore
            self._sem = asyncio.Semaphore(aws_bedrock_simultaneous_queries // 2)
        return await asyncio.gather(*[self._get_single_paired_embedding(i) for i in range(from_idx, to_idx)])


async def populate_vector_db():
    global image_vectors_name, text_vectors_name, embedder, num_datapoints, metadata_lookup, fetch_batch_size, payload_attributes, qdrant_client, collection_name

    for from_idx in range(0, num_datapoints, fetch_batch_size):
        to_idx = min(from_idx + fetch_batch_size, num_datapoints)
        points = []
        img_descr_pairs = await embedder.get_paired_embedding_batch(from_idx, to_idx)
        log.debug(f"Got embedding {from_idx} to {to_idx} out of {num_datapoints} datapoints.")
        for local_idx, (img_vec, text_vec) in enumerate(img_descr_pairs):
            abs_idx = from_idx + local_idx
            # construct the named vectors
            named_vectors = {image_vectors_name: img_vec, text_vectors_name: text_vec}
            # construct the point struct from the payload and named vectors
            points.append(
                models.PointStruct(
                    id=metadata_lookup[abs_idx][index_key],
                    vector=named_vectors,
                    payload={key: metadata_lookup[abs_idx][key] for key in payload_attributes},
                )
            )
        await qdrant_client.upsert(
            collection_name=collection_name,
            points=points,
        )

async def reset_qdrant_indexing_threshold():
    global qdrant_client, collection_name, final_indexing_threshold

    await qdrant_client.update_collection(
        collection_name=collection_name,
        optimizers_config=models.OptimizersConfigDiff(
            indexing_threshold=final_indexing_threshold,
        ),
    )

async def main():
    global embedder

    await setup_qdrant_client()
    await setup_metadata_lookup()
    embedder = Embedder()
    await populate_vector_db()
    await reset_qdrant_indexing_threshold()

if __name__ == '__main__':
    asyncio.run(main())
