# this is the name of the bucket on s3
s3_bucket_name: my-personal-bucket-callingmicron

# this is the path to the hdf5 sample file I created to test s3 upload / download, and random access
sample_hdf5_file_path: /mnt/windows/Users/lordh/Documents/LibraryOfBabel/Projects/fashion_mas/src/exploration/sample_dataset.h5

# this is the path to the sample hdf5 file inside the s3 bucket
sample_hdf5_s3_path: datasets/sample_dataset.h5

# this is the name of the images dataset in the sample hdf5 file
hdf5_images_dataset_name: images

# this is the name of the descriptions dataset in the sample hdf5 file
hdf5_descriptions_dataset_name: descriptions

# this is the path where the random-access image fetched from the hdf5 file should be saved
random_access_image_path: '/mnt/windows/Users/lordh/Documents/LibraryOfBabel/Projects/fashion_mas/src/exploration/random_access_image_{index}.png'
